export const listOfCountries = [
  "Afghanistan", "Åland Islands", "Albania", "Algeria", "American Samoa", "Andorra", "Angola", "Anguilla", "Antigua and Barbuda", "Argentina", "Armenia", "Aruba", "Australia", "Austria", "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bermuda", "Bhutan", "Bolivia", "Bonaire, Sint Eustatius and Saba", "Bosnia and Herzegovina", "Botswana", "Bouvet Island", "Brazil", "British Indian Ocean Territory", "British Virgin Islands", "Brunei", "Bulgaria", "Burkina Faso", "Burundi", "Cabo Verde", "Cambodia", "Cameroon", "Canada", "Cayman Islands", "Central African Republic", "Chad", "Chile", "China", "Christmas Island", "Cocos (Keeling) Islands", "Colombia", "Comoros", "Congo", "Congo, Democratic Republic of the", "Cook Islands", "Costa Rica", "Côte d'Ivoire", "Croatia", "Cuba", "Curaçao", "Cyprus", "Czechia", "Denmark", "Djibouti", "Dominica", "Dominican Republic", "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Eswatini", "Ethiopia", "Falkland Islands", "Faroe Islands", "Fiji", "Finland", "France", "French Guiana", "French Polynesia", "French Southern Territories", "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Gibraltar", "Greece", "Greenland", "Grenada", "Guadeloupe", "Guam", "Guatemala", "Guernsey", "Guinea", "Guinea-Bissau", "Guyana", "Haiti", "Heard Island and McDonald Islands", "Holy See (Vatican City State)", "Honduras", "Hong Kong", "Hungary", "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland", "Isle of Man", "Israel", "Italy", "Jamaica", "Japan", "Jersey", "Jordan", "Kazakhstan", "Kenya", "Kiribati", "Korea, Democratic People's Republic of", "Korea, Republic of", "Kosovo", "Kuwait", "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein", "Lithuania", "Luxembourg", "Macao", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Martinique", "Mauritania", "Mauritius", "Mayotte", "Mexico", "Micronesia, Federated States of", "Moldova", "Monaco", "Mongolia", "Montenegro", "Montserrat", "Morocco", "Mozambique", "Myanmar", "Namibia", "Nauru", "Nepal", "Netherlands", "New Caledonia", "New Zealand", "Nicaragua", "Niger", "Nigeria", "Niue", "Norfolk Island", "Northern Mariana Islands", "North Macedonia", "Norway", "Oman", "Pakistan", "Palau", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Pitcairn Islands", "Poland", "Portugal", "Puerto Rico", "Qatar", "Reunion", "Romania", "Russian Federation", "Rwanda", "Saint Barthelemy", "Saint Helena, Ascension and Tristan da Cunha", "Saint Kitts and Nevis", "Saint Lucia", "Saint Martin", "Saint Pierre and Miquelon", "Saint Vincent and the Grenadines", "Samoa", "San Marino", "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore", "Sint Maarten", "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa", "South Georgia and the South Sandwich Islands", "South Sudan", "Spain", "Sri Lanka", "State of Palestine", "Sudan", "Suriname", "Svalbard and Jan Mayen", "Sweden", "Switzerland", "Syria", "Taiwan", "Tajikistan", "Tanzania", "Thailand", "Timor-Leste", "Togo", "Tokelau", "Tonga", "Trinidad and Tobago", "Tunisia", "Türkiye", "Turkmenistan", "Turks and Caicos Islands", "Tuvalu", "U.S. Virgin Islands", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "United States Minor Outlying Islands", "United States of America", "Uruguay", "Uzbekistan", "Vanuatu", "Venezuela", "Vietnam", "Wallis and Futuna", "Western Sahara", "Yemen", "Zambia", "Zimbabwe"
];

export const countriesWithCodes = [
  "Afghanistan (+93)",
  "Åland Islands (+358)",
  "Albania (+355)",
  "Algeria (+213)",
  "American Samoa (+1)",
  "Andorra (+376)",
  "Angola (+244)",
  "Anguilla (+1)",
  "Antigua and Barbuda (+1)",
  "Argentina (+54)",
  "Armenia (+374)",
  "Aruba (+297)",
  "Australia (+61)",
  "Austria (+43)",
  "Azerbaijan (+994)",
  "Bahamas (+1)",
  "Bahrain (+973)",
  "Bangladesh (+880)",
  "Barbados (+1)",
  "Belarus (+375)",
  "Belgium (+32)",
  "Belize (+501)",
  "Benin (+229)",
  "Bermuda (+1)",
  "Bhutan (+975)",
  "Bolivia (+591)",
  "Bonaire, Sint Eustatius, and Saba (+599)",
  "Bosnia and Herzegovina (+387)",
  "Botswana (+267)",
  "Brazil (+55)",
  "British Indian Ocean Territory (+246)",
  "British Virgin Islands (+1)",
  "Brunei (+673)",
  "Bulgaria (+359)",
  "Burkina Faso (+226)",
  "Burundi (+257)",
  "Cabo Verde (+238)",
  "Cambodia (+855)",
  "Cameroon (+237)",
  "Canada (+1)",
  "Cayman Islands (+1)",
  "Central African Republic (+236)",
  "Chad (+235)",
  "Chile (+56)",
  "China (+86)",
  "Christmas Island (+61)",
  "Cocos (Keeling) Islands (+61)",
  "Colombia (+57)",
  "Comoros (+269)",
  "Congo (+242)",
  "Congo, Democratic Republic of the (+243)",
  "Cook Islands (+682)",
  "Costa Rica (+506)",
  "Côte d'Ivoire (+225)",
  "Croatia (+385)",
  "Cuba (+53)",
  "Curaçao (+599)",
  "Cyprus (+357)",
  "Czechia (+420)",
  "Denmark (+45)",
  "Djibouti (+253)",
  "Dominica (+1)",
  "Dominican Republic (+1)",
  "Ecuador (+593)",
  "Egypt (+20)",
  "El Salvador (+503)",
  "Equatorial Guinea (+240)",
  "Eritrea (+291)",
  "Estonia (+372)",
  "Eswatini (+268)",
  "Ethiopia (+251)",
  "Falkland Islands (+500)",
  "Faroe Islands (+298)",
  "Fiji (+679)",
  "Finland (+358)",
  "France (+33)",
  "French Guiana (+594)",
  "French Polynesia (+689)",
  "Gabon (+241)",
  "Gambia (+220)",
  "Georgia (+995)",
  "Germany (+49)",
  "Ghana (+233)",
  "Gibraltar (+350)",
  "Greece (+30)",
  "Greenland (+299)",
  "Grenada (+1)",
  "Guadeloupe (+590)",
  "Guam (+1)",
  "Guatemala (+502)",
  "Guernsey (+44)",
  "Guinea (+224)",
  "Guinea-Bissau (+245)",
  "Guyana (+592)",
  "Haiti (+509)",
  "Holy See (Vatican City State) (+39)",
  "Honduras (+504)",
  "Hong Kong (+852)",
  "Hungary (+36)",
  "Iceland (+354)",
  "India (+91)",
  "Indonesia (+62)",
  "Iran (+98)",
  "Iraq (+964)",
  "Ireland (+353)",
  "Isle of Man (+44)",
  "Israel (+972)",
  "Italy (+39)",
  "Jamaica (+1)",
  "Japan (+81)",
  "Jersey (+44)",
  "Jordan (+962)",
  "Kazakhstan (+7)",
  "Kenya (+254)",
  "Kiribati (+686)",
  "Korea, Democratic People's Republic of (+850)",
  "Korea, Republic of (+82)",
  "Kosovo (+377)",
  "Kosovo (+381)",
  "Kosovo (+383)",
  "Kosovo (+386)",
  "Kuwait (+965)",
  "Kyrgyzstan (+996)",
  "Laos (+856)",
  "Latvia (+371)",
  "Lebanon (+961)",
  "Lesotho (+266)",
  "Liberia (+231)",
  "Libya (+218)",
  "Liechtenstein (+423)",
  "Lithuania (+370)",
  "Luxembourg (+352)",
  "Macao (+853)",
  "Madagascar (+261)",
  "Malawi (+265)",
  "Malaysia (+60)",
  "Maldives (+960)",
  "Mali (+223)",
  "Malta (+356)",
  "Marshall Islands (+692)",
  "Martinique (+596)",
  "Mauritania (+222)",
  "Mauritius (+230)",
  "Mayotte (+262)",
  "Mexico (+52)",
  "Micronesia, Federated States of (+691)",
  "Moldova (+373)",
  "Monaco (+377)",
  "Mongolia (+976)",
  "Montenegro (+382)",
  "Montserrat (+1)",
  "Morocco (+212)",
  "Mozambique (+258)",
  "Myanmar (+95)",
  "Namibia (+264)",
  "Nauru (+674)",
  "Nepal (+977)",
  "Netherlands (+31)",
  "New Caledonia (+687)",
  "New Zealand (+64)",
  "Nicaragua (+505)",
  "Niger (+227)",
  "Nigeria (+234)",
  "Niue (+683)",
  "Norfolk Island (+672)",
  "Northern Mariana Islands (+1)",
  "North Macedonia (+389)",
  "Norway (+47)",
  "Oman (+968)",
  "Pakistan (+92)",
  "Palau (+680)",
  "Panama (+507)",
  "Papua New Guinea (+675)",
  "Paraguay (+595)",
  "Peru (+51)",
  "Philippines (+63)",
  "Pitcairn Islands (+64)",
  "Poland (+48)",
  "Portugal (+351)",
  "Puerto Rico (+1)",
  "Qatar (+974)",
  "Reunion (+262)",
  "Romania (+40)",
  "Russian Federation (+7)",
  "Rwanda (+250)",
  "Saint Barthelemy (+590)",
  "Saint Helena, Ascension and Tristan da Cunha (+290)",
  "Saint Helena, Ascension and Tristan da Cunha (+247)",
  "Saint Kitts and Nevis (+1)",
  "Saint Lucia (+1)",
  "Saint Martin (+590)",
  "Saint Pierre and Miquelon (+508)",
  "Saint Vincent and the Grenadines (+1)",
  "Samoa (+685)",
  "San Marino (+378)",
  "Sao Tome and Principe (+239)",
  "Saudi Arabia (+966)",
  "Senegal (+221)",
  "Serbia (+381)",
  "Seychelles (+248)",
  "Sierra Leone (+232)",
  "Singapore (+65)",
  "Sint Maarten (+1)",
  "Slovakia (+421)",
  "Slovenia (+386)",
  "Solomon Islands (+677)",
  "Somalia (+252)",
  "South Africa (+27)",
  "South Sudan (+211)",
  "Spain (+34)",
  "Sri Lanka (+94)",
  "State of Palestine (+970)",
  "Sudan (+249)",
  "Suriname (+597)",
  "Svalbard and Jan Mayen (+47)",
  "Sweden (+46)",
  "Switzerland (+41)",
  "Syria (+963)",
  "Taiwan (+886)",
  "Tajikistan (+992)",
  "Tanzania (+255)",
  "Thailand (+66)",
  "Timor-Leste (+670)",
  "Togo (+228)",
  "Tokelau (+690)",
  "Tonga (+676)",
  "Trinidad and Tobago (+1)",
  "Tunisia (+216)",
  "Türkiye (+90)",
  "Turkmenistan (+993)",
  "Turks and Caicos Islands (+1)",
  "Tuvalu (+688)",
  "U.S. Virgin Islands (+1)",
  "Uganda (+256)",
  "Ukraine (+380)",
  "United Arab Emirates (+971)",
  "United Kingdom (+44)",
  "United States Minor Outlying Islands (+1)",
  "United States of America (+1)",
  "Uruguay (+598)",
  "Uzbekistan (+998)",
  "Vanuatu (+678)",
  "Venezuela (+58)",
  "Vietnam (+84)",
  "Wallis and Futuna (+681)",
  "Western Sahara (+212)",
  "Yemen (+967)",
  "Zambia (+260)",
  "Zimbabwe (+263)"
];

export const monthArray = ['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12'];

export const yearArray = [
  "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959",
  "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969",
  "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979",
  "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989",
  "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999",
  "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009",
  "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019",
  "2020", "2021", "2022", "2023", "2024"
];

export const degreeArray = [
  "Degree in Progress (no degree awarded)",
  "High School Diploma/GED",
  "Attendance (No Degree Awarded)",
  "Other",
  "Non-Degree Program",
  "Associate's Degree",
  "Technical Diploma",
  "Higher Degree",
  "Bachelor's Degree",
  "Master's Degree",
  "M.B.A.",
  "Doctorate Degree",
  "M.D.",
  "J.D."
];

export const languageProficiencyArray = ['1 - Minimal Competency', '2 - Limited Competency', '3 - Professional Competency', '4 - Advanced Professional Competency', '5 - Complete Mastery'];

export const languageList = [
  "Afrikaans", "Albanian", "American Sign Language", "Amharic", "Arabic", "Armenian", "Azerbaijani", "Bahasa (Indonesian)",
  "Bengali", "Bosnian", "Bulgarian", "Burmese", "Chinese (Cantonese)", "Chinese (Mandarin)", "Chinese (Other)",
  "Chinese (Shanghai)", "Croatian", "Czech", "Danish", "Dari", "Dutch", "English", "Estonian", "Farsi (Persian)",
  "Finnish", "Flemish", "French", "Georgian", "German", "Greek", "Gujarati", "Hebrew", "Hindi", "Hungarian",
  "Icelandic", "Indian", "Indian (Hindi)", "Indian (Kannada)", "Indian (Konkani)", "Italian", "Japanese", "Khmer",
  "Kiswahili", "Korean", "Kurdish", "Laotian", "Latin", "Latvian", "Lithuanian", "Macedonian", "Malay", "Maori",
  "Navajo", "Norwegian", "Other", "Pashto", "Polish", "Portuguese", "Punjabi", "Romanian", "Russian", "Serbo-Croatian",
  "Slovak", "Somali", "Spanish", "Swahili", "Swedish", "Tagalog (Philippines)", "Tajik", "Tamil (Ceylon)", "Tamil (India)",
  "Telugu", "Thai", "Turkish", "Twi (Ghana)", "Uighur", "Ukrainian", "Urdu (Pakistan)", "Uzbek", "Vietnamese", "Welsh"
];

export const languageLevels = ["Beginner", "Intermediate", "Advanced"]